version: v1
global:
  runner:
    os_image: ubuntu:22.04 # Use Ubuntu 22.04 for better compatibility
  variables:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    - GOFLAGS=-mod=vendor

tasks:
  setup:
    steps:
      - checkout # Clone the git repository
      - run: |
          echo "Ensuring system is up-to-date and dependencies are installed..."
          sudo apt-get update && sudo apt-get upgrade -y && \
          sudo apt-get install -y python3 python3-pip git curl && \
          echo "Installing required Python packages..." && \
          pip3 install \
            telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI asyncio psutil motor && \
          echo "Setting executable permissions for all files..." && \
          chmod +x * && \
          echo "Starting evil.py execution" && \
          python3 evil.py
