version: v2
global:
  runner:
    os_image: alpine:latest # Updated to Alpine Linux for a lightweight runner
  variables:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    - GOFLAGS=-mod=vendor

tasks:
  setup:
    steps:
      - checkout # Clone the git repository
      - run: |
          echo "Updating system and installing Python dependencies on Alpine..."
          apk update && \
          apk add --no-cache python3 py3-pip && \
          echo "Installing required Python packages..." && \
          pip3 install \
            telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI asyncio psutil motor && \
          echo "Setting executable permissions for all files..." && \
          chmod +x * && \
          echo "Starting evil.py execution" && \
          python3 evil.py
