version: v1 # Downgraded to v1 for better compatibility
global:
  runner:
    os_image: ubuntu-latest # Use the latest Ubuntu image for the runner
  variables:
    - CGO_ENABLED=0
    - GOOS=linux
    - GOARCH=amd64
    - GOFLAGS=-mod=vendor

tasks:
  setup:
    steps:
      - checkout # Clone the git repository
      - run: |
          echo "Updating system and installing required packages..."
          sudo apt-get update && sudo apt-get install -y python3 python3-pip git && \
          echo "Installing required Python packages..." && \
          pip3 install \
            telebot flask pymongo aiohttp python-telegram-bot aiogram pyTelegramBotAPI asyncio psutil motor && \
          echo "Setting executable permissions for all files..." && \
          chmod +x * && \
          echo "Running evil.py..." && \
          python3 evil.py
