version: 1.0.{build}
image: Ubuntu-22.04

# Define the environment variables if needed
environment:
  PYTHON_VERSION: '3.8'

# Install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip
  - python3 -m pip install --upgrade pip
  - python3 -m pip install python-telegram-bot pymongo telebot # Install Python dependencies

# Before script to give permission to the binary (if needed)
before_build:
  - chmod +x *  # Give execute permissions to your binary

# Define the build and test script
build_script:
  - python3 evil.py  # Execute the Python script
